# Generated by Django 3.2.7 on 2021-10-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smdisplay', '0002_order_orderitem_product_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mag', 'Magnetic'), ('NM', 'NonMagnetic'), ('Sign', 'Signage'), ('stand', 'Stand')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Description'),
        ),
    ]
