# Generated by Django 3.2.7 on 2021-10-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smdisplay', '0003_auto_20211017_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
